[flags]
1 = "404CTF{uN_r4Il_PoUr_2_Tr4iNs_eU_N0n_dEUx_r4ils_PoUR_1tRa1n}"
2 = "404CTF{m0Y3nN3m3Nt_d1sCR3t_t0ut_d3_M3m3}"
3 = "404CTF{d_Un3_tR1v14l1t3_AbS0lu3}"
4 = "404CTF{It'S_4ll_JuPiT3r__alWaYs_H4s_bE3n}"