apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-acme-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@404ctf.fr
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector: {}
        http01:
          ingress:
            ingressClassName: nginx
